// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/convert": {
            "get": {
                "description": "Convert a specified amount from ARS to USD or USD to ARS using a given rate type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rates"
                ],
                "summary": "Convert amount between ARS and USD",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Amount to convert",
                        "name": "amount",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Currency to convert from (ARS, USD)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Currency to convert to (ARS, USD)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Type of dollar rate to use (e.g., blue, oficial)",
                        "name": "rate_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ConversionResponse"
                        }
                    }
                }
            }
        },
        "/dolar-blue": {
            "get": {
                "description": "Get the blue dollar rate aggregated from different sources",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rates"
                ],
                "summary": "Get blue dollar rate",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Rate"
                        }
                    }
                }
            }
        },
        "/dolar-ccl": {
            "get": {
                "description": "Get the CCL dollar rate aggregated from different sources",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rates"
                ],
                "summary": "Get CCL dollar rate",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Rate"
                        }
                    }
                }
            }
        },
        "/dolar-mep": {
            "get": {
                "description": "Get the MEP dollar rate aggregated from different sources",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rates"
                ],
                "summary": "Get MEP dollar rate",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Rate"
                        }
                    }
                }
            }
        },
        "/dolar-oficial": {
            "get": {
                "description": "Get the oficial dollar rate aggregated from different sources",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rates"
                ],
                "summary": "Get oficial dollar rate",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Rate"
                        }
                    }
                }
            }
        },
        "/dolar-tarjeta": {
            "get": {
                "description": "Get the tarjeta dollar rate aggregated from different sources",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rates"
                ],
                "summary": "Get Tarjeta dollar rate",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Rate"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ConversionResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "converted_amount": {
                    "type": "number"
                },
                "from": {
                    "type": "string"
                },
                "rate_applied": {
                    "type": "number"
                },
                "rate_type": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "model.Rate": {
            "type": "object",
            "properties": {
                "buy": {
                    "type": "number"
                },
                "sell": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Arbolito API",
	Description:      "API for getting different dollar rates in Argentina.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
